### ISSUE TITLE
[FEAT] - [META] Auth lib improvements

### ISSUE THREAD

**Issue by DanCouper** [thingco/shared-frontend-libs#33]
**Which package is this related to?**

Specify the package, or if it is a new package suggest a name.

If this covers multiple packages, **if possible** open an issue for both and PR separately: this will keep the PR's scope as small as possible (plus each package needs separate version bumps & republishing after the fix has been applied).

- [x] `@thingco/auth-flows`
- [ ] `@thingco/graphviz`
- [ ] `@thingco/react-component-library`
- [ ] `@thingco/shared-types`
- [ ] `@thingco/unit-formatter`
- [ ] `@thingco/user-preferences`
- [ ] `@thingco/user-preferences-store-web`
- [ ] `@thingco/user-preferences-store-native`
- [ ] new package (`@thingco/{enter name here}`)

**Is your feature request related to a problem? Please describe.**

Meta issue:

resolves #14 
resolves #22 
resolves #28 
resolves #29 
resolves #30 
resolves #31 
resolves #32
